services:
  # Backend API Service
  - type: web
    name: tennis-marketplace-api
    runtime: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: tennis-marketplace-api
          property: port
      - key: MONGODB_URI
        fromDatabase:
          name: tennis-marketplace-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        fromService:
          type: web
          name: tennis-marketplace-frontend
          property: url

  # Frontend Angular Service
  - type: web
    name: tennis-marketplace-frontend
    runtime: node
    plan: starter
    buildCommand: cd tennis-marketplace && npm install && npm run build
    staticPublishPath: ./tennis-marketplace/dist/baseline-gearhub
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

# Database
databases:
  - name: tennis-marketplace-db
    databaseName: tennis_marketplace
    plan: starter